aws_dbt_snowflake_project:
  outputs:
    dev:
      account: NOMIAUX-VM01435
      database: AIRBNB
      password: PranaM@Jan2026
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: PRAVINPATIL
      warehouse: COMPUTE_WH
    prod:
      account: NOMIAUX-VM01435
      database: AIRBNB_PROD
      password: PranaM@Jan2026
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: PRAVINPATIL
      warehouse: COMPUTE_WH
  target: dev
